version: '3.1'

name: book-library

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  redis:
    image: "redis:latest"
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: book-library
    env_file:
      - .env
    command: >
      sh -c "cd /app/book_library &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    env_file:
      - .env
    command: >
      sh -c "cd /app/book_library/ &&
             celery -A book_library worker -l info"
    depends_on:
      - web
      - redis

volumes:
  mysql-data:
  redis_data:
